from BOOM import BOOM_TMA, BOOM_TMA_INTRET, BOOM_TMA_FETCH_APPROX, BOOM_ISSUE_APPROX, BOOM_RECOVER_APPROX
from ROCKET import ROCKET_TMA
from BOOM_TRACE import BOOM_TRACE_TMA
from FILTERS import get_filter
from TRACE_COLUMNS import BOOM_TRACE_COLUMNS, ROCKET_TRACE_COLUMNS



MODELS_MAP = {
    "ROCKET_TMA": ROCKET_TMA,
    "BOOM_TMA": BOOM_TMA,
    "BOOM_TMA_INTRET": BOOM_TMA_INTRET,
    "BOOM_TMA_FETCH_APPROX": BOOM_TMA_FETCH_APPROX,
    "BOOM_ISSUE_APPROX": BOOM_ISSUE_APPROX,
    "BOOM_RECOVER_APPROX": BOOM_RECOVER_APPROX,
    "BOOM_TRACE_TMA": BOOM_TRACE_TMA,
}